grep: .: Is a directory
grep: ./bin: Is a directory
grep: ./subworkflows: Is a directory
grep: ./subworkflows/local: Is a directory
grep: ./workflows: Is a directory
grep: ./docs: Is a directory
grep: ./docs/images: Is a directory
grep: ./.github: Is a directory
grep: ./.github/workflows: Is a directory
grep: ./.github/ISSUE_TEMPLATE: Is a directory
grep: ./lib: Is a directory
grep: ./.nextflow: Is a directory
grep: ./.nextflow/plr: Is a directory
grep: ./.git: Is a directory
grep: ./.git/objects: Is a directory
grep: ./.git/objects/0d: Is a directory
grep: ./.git/objects/92: Is a directory
grep: ./.git/objects/58: Is a directory
grep: ./.git/objects/9c: Is a directory
grep: ./.git/objects/d9: Is a directory
grep: ./.git/objects/bb: Is a directory
grep: ./.git/objects/d7: Is a directory
grep: ./.git/objects/a2: Is a directory
grep: ./.git/objects/d8: Is a directory
grep: ./.git/objects/e2: Is a directory
grep: ./.git/objects/c0: Is a directory
grep: ./.git/objects/f2: Is a directory
grep: ./.git/objects/4b: Is a directory
grep: ./.git/objects/pack: Is a directory
grep: ./.git/objects/74: Is a directory
grep: ./.git/objects/38: Is a directory
grep: ./.git/objects/65: Is a directory
grep: ./.git/objects/54: Is a directory
grep: ./.git/objects/5e: Is a directory
grep: ./.git/objects/99: Is a directory
grep: ./.git/objects/90: Is a directory
grep: ./.git/objects/d4: Is a directory
grep: ./.git/objects/b6: Is a directory
grep: ./.git/objects/d2: Is a directory
grep: ./.git/objects/b7: Is a directory
grep: ./.git/objects/ff: Is a directory
grep: ./.git/objects/c2: Is a directory
grep: ./.git/objects/f8: Is a directory
grep: ./.git/objects/e0: Is a directory
grep: ./.git/objects/41: Is a directory
grep: ./.git/objects/4f: Is a directory
grep: ./.git/objects/85: Is a directory
grep: ./.git/objects/71: Is a directory
grep: ./.git/objects/2b: Is a directory
grep: ./.git/objects/7a: Is a directory
grep: ./.git/objects/8e: Is a directory
grep: ./.git/info: Is a directory
grep: ./.git/logs: Is a directory
grep: ./.git/logs/refs: Is a directory
grep: ./.git/logs/refs/heads: Is a directory
grep: ./.git/logs/refs/remotes: Is a directory
grep: ./.git/logs/refs/remotes/origin: Is a directory
grep: ./.git/hooks: Is a directory
grep: ./.git/refs: Is a directory
grep: ./.git/refs/heads: Is a directory
grep: ./.git/refs/remotes: Is a directory
grep: ./.git/refs/remotes/origin: Is a directory
grep: ./modules: Is a directory
grep: ./modules/local: Is a directory
grep: ./modules/local/parse_ssds_bam: Is a directory
grep: ./modules/local/multiqc_ssds: Is a directory
grep: ./modules/local/calculatespot: Is a directory
grep: ./modules/local/generate_ssds_coverage: Is a directory
grep: ./modules/nf-core: Is a directory
grep: ./modules/nf-core/ucsc: Is a directory
grep: ./modules/nf-core/ucsc/bedgraphtobigwig: Is a directory
grep: ./modules/nf-core/ucsc/bedgraphtobigwig/tests: Is a directory
grep: ./modules/nf-core/picard: Is a directory
grep: ./modules/nf-core/picard/sortsam: Is a directory
grep: ./modules/nf-core/picard/collectmultiplemetrics: Is a directory
grep: ./modules/nf-core/picard/markduplicates: Is a directory
grep: ./modules/nf-core/picard/markduplicates/tests: Is a directory
grep: ./modules/nf-core/multiqc: Is a directory
grep: ./modules/nf-core/multiqc/tests: Is a directory
grep: ./modules/nf-core/deeptools: Is a directory
grep: ./modules/nf-core/deeptools/plotfingerprint: Is a directory
grep: ./modules/nf-core/trimgalore: Is a directory
grep: ./modules/nf-core/trimgalore/tests: Is a directory
grep: ./modules/nf-core/bwa: Is a directory
grep: ./modules/nf-core/bwa/index: Is a directory
grep: ./modules/nf-core/bwa/index/tests: Is a directory
grep: ./modules/nf-core/bwa/mem: Is a directory
grep: ./modules/nf-core/bwa/mem/tests: Is a directory
grep: ./modules/nf-core/bedtools: Is a directory
grep: ./modules/nf-core/bedtools/sort: Is a directory
grep: ./modules/nf-core/bedtools/bamtobed: Is a directory
grep: ./modules/nf-core/bedtools/bamtobed/tests: Is a directory
grep: ./modules/nf-core/bedtools/makewindows: Is a directory
grep: ./modules/nf-core/fastqc: Is a directory
grep: ./modules/nf-core/fastqc/tests: Is a directory
grep: ./modules/nf-core/samtools: Is a directory
grep: ./modules/nf-core/samtools/idxstats: Is a directory
grep: ./modules/nf-core/samtools/idxstats/tests: Is a directory
grep: ./modules/nf-core/samtools/view: Is a directory
grep: ./modules/nf-core/samtools/view/tests: Is a directory
grep: ./modules/nf-core/samtools/index: Is a directory
grep: ./modules/nf-core/samtools/index/tests: Is a directory
grep: ./modules/nf-core/custom: Is a directory
grep: ./modules/nf-core/custom/dumpsoftwareversions: Is a directory
grep: ./modules/nf-core/custom/dumpsoftwareversions/tests: Is a directory
grep: ./modules/nf-core/custom/dumpsoftwareversions/templates: Is a directory
grep: ./assets: Is a directory
grep: ./conf: Is a directory
